DEFAULT_MAKE_DIR=/opt/pzsdk.ver4.0/make
PZC_TARGET_ARCH=sc2

TARGET=kernel.pz
PZCSRC=../pzc/kernel.pzc

vpath %.pzc ../pzc/

CLANG_OPT += -O3 -std=c++11 -Wall -Wextra -Wfatal-errors

include $(DEFAULT_MAKE_DIR)/default_pzcl_kernel.mk

